import React,{useRef,useState,useEffect}from 'react';const FlutterSheet=({height,animation,backdrop,style,open,setOpen,children})=>{const fluttersheet={title:{color:'#fff'},animation:animation||180,backdrop:{opacity:backdrop||0.3},maxheight:height||'auto',borderradius:24,handle:{color:'rgba(128,128,128,.5)'},backgroundcolor:'#111',};const[drag,setDrag]=useState({startY:null,offset:0,canDrag:!0,isDragging:!1,});const[render,setRender]=useState(!1);const[animate,setAnimate]=useState(!1);const sheetRef=useRef(null);const contentRef=useRef(null);const isHeaderDragging=useRef(!1);const fsComputeMaxHeightPx=()=>(sheetRef.current?parseFloat(getComputedStyle(sheetRef.current).maxHeight):window.innerHeight*0.6)||window.innerHeight*0.6;useEffect(()=>{if(!open)return;window.history.pushState({flutterSheetOpen:!0},'');const fsHandlePopState=(event)=>{if(open){event.preventDefault();setOpen(!1);window.history.pushState({flutterSheetOpen:!1},'')}};window.addEventListener('popstate',fsHandlePopState);return()=>{window.removeEventListener('popstate',fsHandlePopState);if(window.history.state?.flutterSheetOpen){window.history.back()}}},[open,setOpen]);useEffect(()=>{if(open){setRender(!0);setTimeout(()=>setAnimate(!0),0);document.body.style.overflow='hidden';document.body.style.overscrollBehaviorY='contain'}else if(render){setAnimate(!1);document.body.style.overflow='';document.body.style.overscrollBehaviorY='';const t=setTimeout(()=>setRender(!1),fluttersheet.animation);return()=>clearTimeout(t)}
return()=>{document.body.style.overflow='';document.body.style.overscrollBehaviorY=''}},[open,render,fluttersheet.animation]);const fsCalcBackdropOpacity=()=>!open&&!render?0:fluttersheet.backdrop.opacity*(1-Math.min(drag.offset/(fsComputeMaxHeightPx()*0.6),1));const fsIsContentScrollable=()=>contentRef.current?.scrollHeight>contentRef.current?.clientHeight;const fsCanInitiateDrag=()=>!contentRef.current||contentRef.current.scrollTop===0||!fsIsContentScrollable();const fsInitiateDrag=(y,isHeader=!1)=>{if(!isHeader&&contentRef.current?.scrollTop>0)return;isHeaderDragging.current=isHeader;setDrag({startY:y,offset:0,canDrag:!0,isDragging:!0});document.body.style.overflow='hidden'};const fsUpdateDrag=(y)=>{if(!drag.canDrag||drag.startY===null)return;const scrollTop=contentRef.current?.scrollTop??0;if(!isHeaderDragging.current&&scrollTop>0){fsEndDrag();return}
const offset=y-drag.startY;if(offset>=0&&scrollTop===0){setDrag(prev=>({...prev,offset}))}};const fsEndDrag=()=>{document.body.style.overflow='';if(!drag.canDrag){setDrag({startY:null,offset:0,canDrag:!0,isDragging:!1});isHeaderDragging.current=!1;return}
if(drag.offset>100)setOpen(!1);setDrag({startY:null,offset:0,canDrag:!0,isDragging:!1});isHeaderDragging.current=!1};const fsHandleDragStart=(e)=>fsInitiateDrag(e.touches?e.touches[0].clientY:e.clientY);const fsHandleHeaderDragStart=(e)=>fsInitiateDrag(e.touches?e.touches[0].clientY:e.clientY,!0);const fsHandleDragMove=(e)=>fsUpdateDrag(e.touches?e.touches[0].clientY:e.clientY);const fsHandleMouseDown=(e)=>{if(!fsCanInitiateDrag())return;fsHandleDragStart(e);window.addEventListener('mousemove',fsHandleDragMove);window.addEventListener('mouseup',()=>{fsEndDrag();window.removeEventListener('mousemove',fsHandleDragMove)},{once:!0})};const fsHandleHeaderMouseDown=(e)=>{fsHandleHeaderDragStart(e);window.addEventListener('mousemove',fsHandleDragMove);window.addEventListener('mouseup',()=>{fsEndDrag();window.removeEventListener('mousemove',fsHandleDragMove)},{once:!0})};const fsHandleContentScroll=()=>{if(!contentRef.current||drag.startY!==null||drag.isDragging)return;const newCanDrag=contentRef.current.scrollTop===0||!fsIsContentScrollable();if(drag.canDrag!==newCanDrag){setDrag(prev=>({...prev,canDrag:newCanDrag}))}};FlutterSheet.title=({children,style})=>children&&(<center><h2 style={{color:fluttersheet.title.color,fontSize:16,margin:'14px 0px 12px 0px',...style}}>{children}</h2><hr style={{margin:'8px 0px 0px 0px',paddingBottom:0,opacity:'15%'}}/></center>);FlutterSheet.content=({children,style})=>(<div
ref={contentRef}
style={{overflowY:'auto',padding:0,margin:0,flex:1,height:fluttersheet.maxheight,minHeight:0,maxHeight: "100dvh",WebkitOverflowScrolling:'touch',touchAction:drag.isDragging?'none':'pan-y',...style}}
onScroll={fsHandleContentScroll}>{children}</div>);return render?(<div
style={{position:'fixed',top:0,left:0,width:'100vw',height:'100dvh',background:`rgba(0,0,0,${fsCalcBackdropOpacity()})`,zIndex:999999999,transition:drag.startY?'none':`background ${fluttersheet.animation}ms cubic-bezier(.4,0,.2,1), opacity ${fluttersheet.animation}ms cubic-bezier(.4,0,.2,1)`,opacity:open||drag.offset?1:0,pointerEvents:open||drag.offset?'auto':'none'}}
onClick={()=>setOpen(!1)}><div
ref={sheetRef}
style={{position:'fixed',left:0,right:0,bottom:0,background:fluttersheet.backgroundcolor,borderTopLeftRadius:fluttersheet.borderradius,borderTopRightRadius:fluttersheet.borderradius,boxShadow:'0 -2px 18px rgba(0,0,0,0.05)',maxHeight: "100dvh",width:'100vw',transition:drag.startY||drag.offset?'none':`transform ${fluttersheet.animation}ms cubic-bezier(.4,0,.2,1)`,transform:open&&animate?`translateY(${drag.offset}px)`:'translateY(100%)',zIndex:9999999999,overflow:'hidden',display:'flex',flexDirection:'column',...style}}
onClick={(e)=>e.stopPropagation()}
onTouchStart={fsHandleDragStart}
onTouchMove={fsHandleDragMove}
onTouchEnd={fsEndDrag}
onMouseDown={fsHandleMouseDown}><div
style={{userSelect:'none',cursor:'grab',padding:0,flexShrink:0}}
onTouchStart={(e)=>{e.stopPropagation();fsHandleHeaderDragStart(e)}}
onTouchMove={(e)=>{e.stopPropagation();fsHandleDragMove(e)}}
onTouchEnd={(e)=>{e.stopPropagation();fsEndDrag(e)}}
onMouseDown={(e)=>{e.stopPropagation();fsHandleHeaderMouseDown(e)}}><center><div style={{height:4,width:42,marginTop:12,background:fluttersheet.handle.color,borderRadius:'999px',cursor:'grab',touchAction:'none'}}/></center>{children}</div></div></div>):null};export default FlutterSheet